### ISSUE TITLE
Netzwerk- NodeJs Server

### ISSUE THREAD

**Issue by GebhardtFe** [SE2-Gruppe5/joking-hazard#15]
Implemented with socket.io

- [x] Room Handler
  - Join, Create, Leave, Close Room
  - Get Players
  - ...
- [x] User Handler
  - Change name
  - Points
- [x] Logging
  - Install Logging Handler
  - Implement logging everywhere
- [x] Tests
  - Install Test Framework (Jest)
  - Implement tests
- [x] Install on server

**Comment by derfl007** [comment]
Server URL: https://joking-hazard-server.hosting143363.a2e82.netcup.net

Server Admin UI: https://admin.socket.io  
Login mit:
- Server https://joking-hazard-server.hosting143363.a2e82.netcup.net/admin
- User: admin
- Password: Mich fragen!
