### ISSUE TITLE
Netzwerk - ClientSocket

### ISSUE THREAD

**Issue by GebhardtFe** [SE2-Gruppe5/joking-hazard#16]
Stellt die Verbindung mit dem Server der die einzelnen Spieler verbindet her

**Comment by derfl007** [comment]
Implementierung mit [Socket.io](https://socket.io/blog/native-socket-io-and-android/)

**Comment by derfl007** [comment]
Grundstruktur wurde hinzugefügt, der Rest wird in den jeweiligen Issues bearbeitet
