### ISSUE TITLE
Rollen bestimmen

### ISSUE THREAD

**Issue by derfl007** [SE2-Gruppe5/joking-hazard#2]
- [x] Developer: @derfl007, @GebhardtFe 
- [x] Dokumentation: @nico0210, @derfl007  
- [x] Tests: @floratsch, @nico0210 
- [x] UI: @annalenamariaroettl, @floratsch  
- [x] Architekt: @GebhardtFe, @annalenamariaroettl

**Comment by GebhardtFe** [comment]
Rollen zugeteilt
