### ISSUE TITLE
Spiellogik - Voting System

### ISSUE THREAD

**Issue by derfl007** [SE2-Gruppe5/joking-hazard#24]
Votingsystem für den Punkterichter

- UI für die Auswahl der Karte
- Punktevergabe

**Comment by GebhardtFe** [comment]
- [ ] Dynamisch UI für 3 oder 4 Spieler

- [ ] Testen der UI

- [ ] Aufruf der UI durch das Spiel (Netzwerk Event)

- [ ] Punktevergabe

**Comment by derfl007** [comment]
Complete by Sprint 4
