### ISSUE TITLE
Spiellogik - Drag'n'Drop

### ISSUE THREAD

**Issue by derfl007** [SE2-Gruppe5/joking-hazard#9]
Die Spielkarten per Drag and Drop zur gewünschten bzw. richten Stelle ziehen;

**Comment by nico0210** [comment]
Drag and Drop Funktion fertig implementiert; Es fehlt nur noch das Anhängen der Spielakarten (Spielkarten enstehen in Issue aus Sprint 3) an die Methoden;

**Comment by derfl007** [comment]
Complete by Sprint 4
